/// Go compatibility tests.
///
/// These tests validate against test vectors generated by the Go reference
/// implementation (segmentio/ksuid). In CI, vectors are generated fresh by
/// running `tests/go/main.go`. Locally, they validate against the checked-in
/// `tests/go_vectors.json` file.
use ksuid::Ksuid;

#[derive(Debug, serde::Deserialize)]
struct TestVector {
    description: String,
    timestamp: u32,
    payload_hex: String,
    raw_hex: String,
    string: String,
    next_string: String,
    prev_string: String,
}

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

fn load_vectors() -> Vec<TestVector> {
    // Try CI-generated vectors first, then fall back to checked-in file
    let path = if std::path::Path::new("tests/go_vectors_live.json").exists() {
        "tests/go_vectors_live.json"
    } else {
        "tests/go_vectors.json"
    };
    let data = std::fs::read_to_string(path)
        .unwrap_or_else(|_| panic!("Cannot read {path}. Run the Go vector generator first."));
    serde_json::from_str(&data).expect("Invalid JSON in test vectors")
}

#[test]
fn test_go_compat_encode() {
    for v in &load_vectors() {
        let payload_bytes = hex_to_bytes(&v.payload_hex);
        let payload: [u8; 16] = payload_bytes.try_into().expect("payload must be 16 bytes");
        let k = Ksuid::from_parts(v.timestamp, &payload);
        assert_eq!(
            k.to_string(),
            v.string,
            "encode mismatch for '{}': from_parts({}, {}) produced {} instead of {}",
            v.description,
            v.timestamp,
            v.payload_hex,
            k,
            v.string
        );
    }
}

#[test]
fn test_go_compat_decode() {
    for v in &load_vectors() {
        let k = Ksuid::parse(&v.string).unwrap_or_else(|e| {
            panic!("parse failed for '{}': {}: {}", v.description, v.string, e)
        });
        assert_eq!(
            k.timestamp(),
            v.timestamp,
            "timestamp mismatch for '{}'",
            v.description
        );
        let expected_payload = hex_to_bytes(&v.payload_hex);
        assert_eq!(
            k.payload().as_slice(),
            expected_payload.as_slice(),
            "payload mismatch for '{}'",
            v.description
        );
    }
}

#[test]
fn test_go_compat_hex() {
    for v in &load_vectors() {
        let k = Ksuid::from_hex(&v.raw_hex).unwrap_or_else(|e| {
            panic!(
                "from_hex failed for '{}': {}: {}",
                v.description, v.raw_hex, e
            )
        });
        assert_eq!(
            k.to_string(),
            v.string,
            "hex->string mismatch for '{}'",
            v.description
        );
        assert_eq!(
            k.to_hex().to_lowercase(),
            v.raw_hex.to_lowercase(),
            "to_hex roundtrip mismatch for '{}'",
            v.description
        );
    }
}

#[test]
fn test_go_compat_roundtrip() {
    for v in &load_vectors() {
        let k = Ksuid::parse(&v.string).unwrap();
        assert_eq!(
            k.to_string(),
            v.string,
            "roundtrip mismatch for '{}'",
            v.description
        );
    }
}

#[test]
fn test_go_compat_next() {
    for v in &load_vectors() {
        let k = Ksuid::parse(&v.string).unwrap();
        let next = k.next();
        assert_eq!(
            next.to_string(),
            v.next_string,
            "next() mismatch for '{}': expected {}, got {}",
            v.description,
            v.next_string,
            next
        );
    }
}

#[test]
fn test_go_compat_prev() {
    for v in &load_vectors() {
        let k = Ksuid::parse(&v.string).unwrap();
        let prev = k.prev();
        assert_eq!(
            prev.to_string(),
            v.prev_string,
            "prev() mismatch for '{}': expected {}, got {}",
            v.description,
            v.prev_string,
            prev
        );
    }
}

#[test]
fn test_go_compat_raw_bytes() {
    for v in &load_vectors() {
        let raw = hex_to_bytes(&v.raw_hex);
        let arr: [u8; 20] = raw.try_into().expect("raw must be 20 bytes");
        let k = Ksuid::from_bytes(&arr);
        assert_eq!(
            k.to_string(),
            v.string,
            "raw bytes->string mismatch for '{}'",
            v.description
        );
    }
}
